language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
  - git clone --depth=50 https://github.com/google/googletest.git lib/googletest
  - sudo apt-get install -qq g++-4.8 libboost-math1.55-dev libboost-random1.55-dev
  - export CXX="g++-4.8"
  - CC="gcc-4.8"
  - echo ${CXX}
  - ${CXX} --version

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
