language: cpp

compiler:
  - gcc

install:
  - git clone --depth=50 https://github.com/google/googletest.git lib/googletest
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - CC="gcc-4.8"
  - echo ${CXX}
  - ${CXX} --version

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
